name: social-buying-api
recipe: mean
config:
  port: 3030
  build:
    - npm install @feathersjs/cli
  command: npm dev
tooling:
  feathers:
    service: appserver
    description: "FeathersJS"
    cmd:
      - /app/node_modules/.bin/feathers
